baseURL = "https://yu-kuri.github.io/"
languageCode = "ja"
title = "雑記置き場"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "yu-kuri"
  description = "日々の雑記"
  github = "yu-kuri"
  url = "https://yu-kuri.github.io"
  avatar = "/images/avatar.png"
  favicon = "/images/avatar.png"
  headerIcon = "/images/avatar.png"
  rss = true
  lastmod = true

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[taxonomies]
  category = "categories"
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = true
